#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

mv /tmp/contents/static/mozilla.gpg /etc/apt/keyrings/
mv /tmp/contents/static/mozilla.list /etc/apt/sources.list.d/

aptitude update ; aptitude install -y curl firefox firefox-l10n-es-es openjdk-17-jre libnss3-tools xdg-utils xvfb

useradd -m -u 1000 -G sudo user
chsh -s /bin/bash user
su user xdg-mime default afirma.desktop x-scheme-handler/afirma
su user xvfb-run firefox &
pid=$!
sleep 5
kill $pid

curl 'https://estaticos.redsara.es/comunes/autofirma/currentversion/AutoFirma_Linux_Debian.zip' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document' -H 'Sec-Fetch-Mode: navigate' -H 'Sec-Fetch-Site: none' -H 'Sec-Fetch-User: ?1' -H 'Priority: u=1' --output /tmp/autofirma.zip

unzip -d /tmp /tmp/autofirma.zip

